#!/bin/sh 
 
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E 'src/(index\.tpl|site\.json|generate\.py)') 


if [ -n "$CHANGED_FILES" ] || [ ! -f index.html ]; then 
    echo 'Changes detected in template or config, generating index.html...' 
    .venv/Scripts/python.exe src/generate.py || exit 1 
    git add index.html 
    echo "### changed files: [$CHANGED_FILES]"
else
    echo "### no re-generation"
fi 

exit 0 
