#!/bin/sh 
 
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM) # | grep -E 'src/(index\.tpl|site\.json|generate\.py)|static/css/styles\.css') 

echo '### changed files: [$CHANGED_FILES]; generating index.html... ' 
.venv/Scripts/python.exe src/generate.py || exit 1 
git add index.html 

exit 0 
