name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install jinja2

    - name: Generate HTML
      run: |
        python <<EOF
        import json
        from jinja2 import Environment, FileSystemLoader
        
        env = Environment(loader=FileSystemLoader('src'))
        template = env.get_template('index.tpl')
        
        with open('src/site.json') as f:
            data = json.load(f)
        
        html = template.render(site=data['site'])
        
        with open('dist/index.html', 'w') as f:
            f.write(html)
        EOF

    - name: Deploy to Server
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "dist/index.html"
        target: "."
